### ISSUE TITLE
There's something wrong with it

### ISSUE THREAD

**Issue by OPStellar** [Yochyo/Sprite-Resource-Downloader#2]
Whenever I try to run it, I get this response:
```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal Capacity: -1
	at java.base/java.util.ArrayList.<init>(ArrayList.java:160)
	at de.yochyo.spriteresourcedownloader.MainKt.getLinksToSprite(Main.kt:57)
	at de.yochyo.spriteresourcedownloader.MainKt.main(Main.kt:19)
```

**Comment by stawze** [comment]
Same
